name: hello word job
on:
 push:
  branches:
   - main
job:
  hello-word-try
   runs-on: ubuntu-latest
   steps:
     - name: checkout code
        uses: actions/checkout@v3
     - name: print message
        run: echo "hello this is to test gh action"
    
