name: git hub actions
on:
 push:
  branches:
   - main
 jobs:
  hello_word_job
     runs-on: ubuntu-latest
     steps:
      - name: checkout code
        uses: actions./checkout@v3
      - name: print message
        run: echo "finally i got it"
