name: git hub actions
on: 
 push:
  branches:
   - main
jobs:
 hello_git_hub_actions:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: print message
      run: echo " hellooo  im doing it finalllyyyy"
