name: hello world
on:
 push:
  branches:
   - main
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: print message
        run: echo "this is to test git hub actions"
  run-pytest:
      runs-on: ubuntu-latest
      steps: 
         - name: checkout code
           uses: actions/checkout@v3
         - name: setup python
           uses: actions/setup-python@v3
           with:
             python-version: 3.9
         - name: install dependency's 
           run: 
             python -m pip install --upgrade pip
             pip install pytest
         - name: test cases
           run: pytest
