name: hello word program
on:
 push:
  branches:
   - main
jobs:
  hello_github_actions:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       used: actions/checkout@v3
     - name: print message 
       run: echo " hii git hub actions"
