name: git hub actions
on: 
 push:
  branches:
   - main
jobs:
 hello_git_hub_actions:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: print message
      run: echo " hellooo  im doing it finalllyyyy"
 run_pytest:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: setup env
      uses: actions/setup-python@v3
      with:
       python-version: 3.9
    - name: installing depenencies
      run:
       python -m pip install --upgrade pip
       pip install pytest
    - name: run testcases
      run: pytest
