name: Github actions test
on: 
 push:
  branches:
   - main
jobs:
 git_hub_test:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: print message
      run: echo "hello finally done"
