name: hello world
on:
 push:
  brnach:
   - main
 job: hello_world_jon
 runs-on: ubuntu-latest
 steps:
     - name: checkout code
       uses: actions/checkout@v3
     - name: print message
       run: echo "this is to test git hub actions"
